#!/usr/bin/python3
"""Defines the BaseModel class"""
import uuid
from datetime import datetime
import json


class BaseModel:
    """
    Defines all common attributes/methods for other classes

    Attributes:
        id (str): a unique id generated by the uuid module
        created_at (class): Time of instance creation
        updated_at (class): Time instance is updated

    """
    def __init__(self):
        """
        Public and private instance attributes init
        """
        self.id = str(uuid.uuid4())
        self.created_at = datetime.now()
        self.updated_at = datetime.now()

    def __str__(self):  #: Returns a string obj. of the Class Obj.
        print(f"[{self.__name__}] ({self.id}) <{self.__dict__}")

    def save(self):  #: Updates the public instance attr. updated_at
        self.updated_at = datetime.now()

    def to_dict(self):
        """Returns a dict containing all keys/values of __dict__ of the instance"""
        dict = json.dumps(
            {
                '__class__': self.__name__
            }
        )
        return json.loads(dict)
